### ISSUE TITLE
请问怎么添加客服？

### ISSUE THREAD

**Issue by Lymlair** [polk6/vue-im#2]
搭建服务器和绑定socketio都是写在webpack.dev里的，请问为什么要写在这里。还有最开始的客户端和服务端使用map定义的，添加服务端的时候用的map.set()，这样是不是把以前的客服覆盖了？粗略理解，还望解答。

**Comment by polk6** [comment]
这里为了省事，把socket.io放到了webpack.dev里。
在实际项目中，后端是独立的一块，维护服务端列表和客户端列表。
