### ISSUE TITLE
请教common_chat.vue组件中的问题

### ISSUE THREAD

**Issue by Lymlair** [polk6/vue-im#3]
非常感谢你上次的解答，我本来打算不再麻烦你了，但是这次遇到这个问题我确实看不太懂。
在common文件夹下，common_chat.vue组件第227-253行，window.getSelection相关的API，因为没怎么接触过，而且vue中添加dom的方法我也没用过，希望可以添加一点相应的注释。
另外，关于表情选择有个bug，当聊天页面一开始没有任何内容时，此时选择表情表情不会出现再聊天框内，并且控制台会报错，只有手动点击使聊天框聚焦后，再选择表情才有效。

**Comment by polk6** [comment]
很抱歉现在才回，已提交以下2个问题的结局方案：
1.common_chat.vue组件第227-253行，window.getSelection相关的API
答：window.getSelection是跟文本选中相关的，这里的场景是选中文本后，输入内容如何替换选中的文本。

2.表情选择有个bug，当聊天页面一开始没有任何内容时，此时选择表情表情不会出现再聊天框内，并且控制台会报错，只有手动点击使聊天框聚焦后，再选择表情才有效。
答：已在common_chat.vue的mounted事件中添加获取input输入框的功能。
