### ISSUE TITLE
发现在输入框输入文字过快，会造成输入汉字变“拼音”bug

### ISSUE THREAD

**Issue by zerogzs** [polk6/vue-im#6]
当keyup事件触发时，绑定的数据还没变更，虽有设置延后访问，但是打字过快还是会出现该情况，请问是否有更好的解决方案呢？

**Comment by polk6** [comment]
有复现流程吗？

**Comment by zhangxiangruZ** [comment]
你好，能给个联系方式吗，有写问题交流下

**Comment by zhangxiangruZ** [comment]
着急，可以付钱

**Comment by polk6** [comment]
可加q 282753552 或邮箱 po2008@outlook.com

**Comment by polk6** [comment]
有事情可发邮件 po2008@outlook.com

**Comment by zerogzs** [comment]
![image.png](https://i.loli.net/2020/05/12/kpogWhqS5CEF8Vd.png)

**Comment by polk6** [comment]
已进行修复
